package io.vidocq.heisenberg.cdi.jpmsit;

import io.vidocq.heisenberg.cdi.internal.BulkheadStateRegistryBean;
import io.vidocq.heisenberg.cdi.internal.FaultToleranceInterceptor;
import io.vidocq.heisenberg.cdi.internal.HeisenbergExtension;
import io.vidocq.heisenberg.cdi.internal.StateRegistryBean;
import io.vidocq.vauban.core.container.VaubanContainer;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * Runs on the MODULE PATH (this is a named module with a {@code module-info}). It boots a Vauban
 * container programmatically and obtains the {@code @Retry} bean via {@link VaubanContainer#select(Class)}
 * — deliberately NOT through {@code @Inject} into the test instance, so nothing reflects into the test
 * class and the module needs no {@code opens}.
 *
 * <p>What this proves, that a class-path test cannot: {@code @Retry} interception fires on a strict
 * module path with a BUILD-TIME generated {@code $$Intercepted} subclass and the generated
 * {@code VaubanComponentProvider}, with zero {@code opens} to {@code io.vidocq.vauban.core}. The
 * application bean ({@link FaultToleranceService}, in this module) AND the {@code FaultToleranceInterceptor}
 * (in heisenberg-cdi-vauban, whose {@code @Inject} state-registry fields are package-private) are all
 * instantiated and field-injected in-module by their generated providers; the interceptor's public
 * {@code @AroundInvoke} runs the retry policy without opens.</p>
 */
class FaultToleranceModulePathTest {

    @Test
    void retries_on_the_module_path_without_opens() throws Exception {
        // The $$Intercepted subclass is a BUILD-TIME class (generated by the APT), loadable by name.
        assertNotNull(
                Class.forName("io.vidocq.heisenberg.cdi.jpmsit.FaultToleranceService$$Intercepted"),
                "the APT must have generated FaultToleranceService$$Intercepted at build time");

        FaultToleranceService.CALLS.set(0);
        VaubanContainer container = VaubanContainer.builder()
                .addBeanClass(HeisenbergExtension.class)
                .addBeanClass(FaultToleranceInterceptor.class)
                .addBeanClass(StateRegistryBean.class)
                .addBeanClass(BulkheadStateRegistryBean.class)
                .addBeanClass(FaultToleranceService.class)
                .build();
        try {
            FaultToleranceService svc = container.select(FaultToleranceService.class);
            try {
                svc.call();
            } catch (RuntimeException expected) {
                // Expected: the retries are exhausted and the last failure propagates.
            }

            // @Retry(maxRetries = 3) → 1 initial call + 3 retries = 4 invocations. If it were 1, the
            // FaultToleranceInterceptor would not be wired (no module-path interception, or a field that
            // could not be injected without opens).
            assertEquals(4, FaultToleranceService.CALLS.get(),
                    "the @Retry interceptor must drive 4 invocations in-module, with no opens");
        } finally {
            container.close();
        }
    }
}
