/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.heisenberg.it.openliberty;

import io.vidocq.heisenberg.api.FtMetricsRecorder;
import jakarta.enterprise.context.ApplicationScoped;
import java.lang.reflect.Method;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Records the bean class every metric is published under: the class the application wrote, not a
 * subclass generated by the container (Vauban's {@code $$Intercepted}, Weld's
 * {@code $Proxy$_$$_WeldSubclass}).
 */
@ApplicationScoped
public class RecordingFtMetricsRecorder implements FtMetricsRecorder {

    private final Set<String> beanClasses = ConcurrentHashMap.newKeySet();

    public Set<String> beanClasses() {
        return Set.copyOf(beanClasses);
    }

    private void seen(Class<?> beanClass) {
        beanClasses.add(beanClass.getName());
    }

    @Override
    public void register(Class<?> beanClass, Method method, boolean hasRetry, boolean hasTimeout,
            boolean hasCircuitBreaker, boolean hasBulkhead, boolean hasFallback, boolean asyncBulkhead) {
        seen(beanClass);
    }

    @Override
    public void recordInvocation(Class<?> beanClass, Method method, boolean succeeded,
            boolean fallbackApplied, boolean fallbackDefined) {
        seen(beanClass);
    }

    @Override
    public void recordRetry(Class<?> beanClass, Method method, int retryCount, RetryResult result) {
        seen(beanClass);
    }

    @Override
    public void recordTimeout(Class<?> beanClass, Method method, boolean timedOut, long durationNanos) {
        seen(beanClass);
    }

    @Override
    public void recordCircuitBreakerCall(Class<?> beanClass, Method method, CBCallResult result) {
        seen(beanClass);
    }

    @Override
    public void notifyCircuitBreakerStateChange(Class<?> beanClass, Method method, CBState from, CBState to) {
        seen(beanClass);
    }

    @Override
    public void recordBulkheadAccepted(Class<?> beanClass, Method method, long waitNanos, long runNanos) {
        seen(beanClass);
    }

    @Override
    public void recordBulkheadRejected(Class<?> beanClass, Method method) {
        seen(beanClass);
    }

    @Override
    public void bulkheadRunningDelta(Class<?> beanClass, Method method, int delta) {
        seen(beanClass);
    }

    @Override
    public void bulkheadWaitingDelta(Class<?> beanClass, Method method, int delta) {
        seen(beanClass);
    }
}
